### PR TITLE
[MIG] account_periodical_invoicing to v9

### PR DESCRIPTION
**Pull request by andreparames**
Hello! We (ThinkOpen Solutions) have ported your very useful module to Odoo v9, and we'd like to contribute that back if you are interested. This version is now in production and it's been working fine.

We have also translated this module to Portuguese. Assuming you're interested in the two submissions, should we add the translations to this PR or create a new one later?

Thank you!

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for migrating it!

Can you please take care of the errors on Travis? And please restore the grouping behaviour that is present in last version on the module. The rest seems OK for me.

**Comment by andreparames** [comment]
Thanks for the feedback! We're on it!

By the way, it seems the Odoo automated tests are failing due to a missing `wkhtmltopdf`, is that expected behavior?

**Comment by pedrobaeza** [comment]
I have added the needed configuration for wkhtmltopdf in this commit: https://github.com/serviciosbaeza/serviciosbaeza-odoo-addons/commit/81910ab7c84954d07cf1a5b5ec6b55a78b09be87.

Please rebase to get it.

**Comment by andreparames** [comment]
Sorry, it seems the wkhtmltopdf version installed is too old: 

> Wkhtmltopdf failed (error code: 2). Message: The switch --header-spacing, is not support using unpatched qt, and will be ignored.The switch --header-html, is not support using unpatched qt, and will be ignored.The switch --footer-html, is not support using unpatched qt, and will be ignored.

**Comment by pedrobaeza** [comment]
It's not a question of aging, but it's not a QT patched version, but it's strange, because this one has been used in other OCA repositories. Anyway, don't focus for now on that, and do the other tasks. I'll check further.

**Comment by mgielissen** [comment]
I've tested the module on the latest V9c version and works great!

**Comment by pedrobaeza** [comment]
Thank you for the contribution. I proceed with the merge then.

**Pull request merged**
